# Generated by Django 5.2.1 on 2025-10-15 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=50, null=True)),
                ('books_title', models.CharField(max_length=50, null=True)),
                ('books_descripation', models.TextField()),
                ('books_author', models.CharField(max_length=50, null=True)),
                ('media', models.ImageField(max_length=250, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='books_issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('books_name', models.CharField(max_length=50, null=True)),
                ('phon_no', models.IntegerField(unique=True)),
                ('issue_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment1', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_ss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.book_s')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
